### ISSUE TITLE
"undefined" TypeError in getAnimeFromURL

### ISSUE THREAD

**Issue by tshrpl** [tarunm20/4anime-scraper#5]
test file:
```js
user@Notebook:~/desktop/4anime_scraper$ cat blah.js

const anime = require('4anime-scraper');
anime.getAnimeFromURL("https://4anime.to/anime/bakemonogatari").then(res => {
	console.log(res);
});
/*anime.getAnimeFromURL("https://4anime.to/anime/the-god-of-high-school").then(res => {
	console.log(res);
});*/
```

output:
```node
user@Notebook:~/desktop/4anime_scraper$ node blah.js

TypeError: Cannot read property 'split' of undefined
    at /home/user/desktop/4anime_scraper/node_modules/4anime-scraper/index.js:56:39
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
undefined
```

**Comment by tarunm20** [comment]
Hey @tshrpl, I found the error and I implemented a solution but I'll be doing some testing before I push it to the repo, thanks for the issue.
